--- Migrate UP Person

CREATE TABLE Person (
	PersonID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	PersonName TEXT UNIQUE NOT NULL,
	PersonFirstname TEXT,
	PersonSurname TEXT,
	IsGlobalAdmin BOOL NOT NULL DEFAULT FALSE
);
