--- Migrate UP ApiToken

CREATE TABLE ApiToken (
	ApiTokenID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	PersonID INTEGER REFERENCES Person(PersonID) ON DELETE CASCADE,
	TokenHash TEXT NOT NULL
);
